baseURL = 'https://tmcdigitech.github.io/unity/'
languageCode = 'en-au'
title = 'TMC - Unity'
theme = ["hugo-geekdoc", "reveal-hugo"]

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
# pygmentsCodeFences = true
disablePathToLower = true

publishDir = "docs"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.goldmark.renderer]
unsafe = true
